name: "Basis"
description: "Basis"
outputs:
  is-finished:
    description: "Whether the program has finished or not"
    value: ${{ steps.basis.outputs.IS_FINISHED }}
# このアクションは `context.json` というJSONファイルがプロジェクトルートに存在することを仮定している。
runs:
  using: composite
  steps:
    - name: Output program state
      id: basis
      shell: bash
      working-directory: program-state
      run: |
        cat program
        cat <<<'' # break line

        # Display in integer order instead of dictionary order
        cat memory_?
        cat memory_??
        cat memory_???
        cat memory_????
        cat memory_?????
        cat <<<'' # break line

        # Display in integer order instead of dictionary order
        cat transition-function_? || true
        cat transition-function_?? || true
        cat transition-function_??? || true
        cat transition-function_???? || true
        cat <<<'' # break line

        cat current-program-position
        cat <<<'' # break line

        cat current-memory-position
        cat <<<'' # break line

        cat stdin
        cat <<<'' # break line

        cat stdout
        cat <<<'' # break line


        cat <<<'IS_FINISHED=true' >> $GITHUB_OUTPUT
