name: "Basis"
description: "Basis"
outputs:
  is-finished:
    description: "Whether the program has finished or not"
    value: ${{ steps.basis.outputs.IS_FINISHED }}
# This action assumes that the state of the Brainfuck interpreter is stored in the directory `program-state`.
runs:
  using: composite
  steps:
    - name: Output program state
      id: basis
      shell: bash
      working-directory: program-state
      run: |
        cat <<<'program'
        cat program

        # Display in integer order instead of dictionary order
        cat <<<'
        memory'
        cat memory_?
        cat memory_??
        cat memory_???
        cat memory_????
        cat memory_?????

        # Display in integer order instead of dictionary order
        cat <<<'
        transition function'
        cat transition-function_? || true
        cat transition-function_?? || true
        cat transition-function_??? || true
        cat transition-function_???? || true

        cat <<<'
        current program position'
        cat current-program-position

        cat <<<'
        current memory position'
        cat current-memory-position

        cat <<<'
        stdin'
        cat stdin

        cat <<<'
        stdout'
        cat stdout


        cat <<<'IS_FINISHED=true' >> $GITHUB_OUTPUT
