name: Empty commit to branch
description: Empty commit to a branch. This action is used to fire some branches.

inputs:
  personal-access-token:
    description: Personal Access Token of GitHub
    required: true
  branch-name:
    description: Branch name to be committed
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch-name }}
        token: ${{ inputs.personal-access-token }} # NOTE: Cannot use `GITHUB_TOKEN` to fire workflow recursively
    - name: Fire Brainfuck interpreter
      shell: bash
      run: |
        # c.f. https://zenn.dev/lollipop_onl/articles/eoz-gha-push-diffs
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit --allow-empty -m 'Empty commit'
        git push -u origin ${{ inputs.branch-name }}
