name: ","
description: ", branch"
# This action assumes that the state of the Brainfuck interpreter is stored in the directory `program-state`.
runs:
  using: composite
  steps:
    - name: Evaluates values to be used later
      shell: bash
      working-directory: program-state
      run: |
        cat <<< "CURRENT_PROGRAM_POSITION=$(cat current-program-position)" >> $GITHUB_ENV
        cat <<< "CURRENT_MEMORY_POSITION=$(cat current-memory-position)" >> $GITHUB_ENV
        cat <<< "CURRENT_MEMORY_VALUE=$(cat memory_$(cat current-memory-position))" >> $GITHUB_ENV
        cat <<< "STDIN=$(cat stdin)" >> $GITHUB_ENV

    - name: Exit if no input
      shell: bash
      if: ${{ env.STDIN == '' }}
      run: exit 1

    - name: Update program state
      shell: bash
      working-directory: program-state
      run: |
        cat <<< $(( $CURRENT_PROGRAM_POSITION + 1 )) >current-program-position
        cat <<< $( cat "../character-to-number/${STDIN:0:1}" ) >$(cat <<< "memory_$(cat current-memory-position)")
        cat <<< "${STDIN:1}" >stdin
