name: "]"
description: "] branch"
# This action assumes that the state of the Brainfuck interpreter is stored in the directory `program-state`.
runs:
  using: composite
  steps:
    - name: Evaluates values to be used later
      shell: bash
      working-directory: program-state
      run: |
        cat <<< "CURRENT_PROGRAM_POSITION=$(cat current-program-position)" >> $GITHUB_ENV
        cat <<< "JUMP_TO=$(cat "transition-function_$(cat current-program-position)")" >> $GITHUB_ENV
        cat <<< "CURRENT_MEMORY_VALUE=$(cat memory_$(cat current-memory-position))" >> $GITHUB_ENV

    - name: Update program state (if memory value is not 0)
      shell: bash
      working-directory: program-state
      run: |
        cat <<< $(( $JUMP_TO  + 1 )) >current-program-position
      if: ${{ env.CURRENT_MEMORY_VALUE != 0 }}

    - name: Update program state (if memory value is 0)
      shell: bash
      working-directory: program-state
      run: |
        cat <<< $(( $CURRENT_PROGRAM_POSITION + 1 )) >current-program-position
      if: ${{ env.CURRENT_MEMORY_VALUE == 0 }}
