name: Brainfuck interpreter by GitHub Actions

on:
  push:
    branches:
      - dummy-main

jobs:
  entrypoint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Restore context
        uses: actions/cache/restore@v4
        with:
          path: |
            context.json
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Exit if `content.json` does not exist
        run: if [ ! -e context.json ]; then exit 1; fi

      #==============================================================================
      # Main
      - run: cat context.json
      - name: Evaluates values to be used later
        id: values
        run: |
          echo "CURRENT_PROGRAM_POSITION=$(cat context.json | jq .currentProgramPosition)" >> $GITHUB_OUTPUT
          echo "PROGRAM_LENGTH=$(cat context.json | jq '.program | length')" >> $GITHUB_OUTPUT
          echo "CURRENT_CHARACTER=$(cat context.json | jq -r '.program' | cut -c $(( 1 + $(cat context.json | jq .currentProgramPosition) )))" >> $GITHUB_OUTPUT

      - name: ">"
        uses: ./.github/actions/>/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '>' }}

      - name: "<"
        uses: ./.github/actions/</
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '<' }}

      - name: "+"
        uses: ./.github/actions/+/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '+' }}

      - name: "-"
        uses: ./.github/actions/-/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '-' }}

      - name: "."
        uses: ./.github/actions/_./
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '.' }}

      - name: ","
        uses: ./.github/actions/,/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == ',' }}

      - name: "["
        uses: ./.github/actions/[/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '[' }}

      - name: "]"
        uses: ./.github/actions/]/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == ']' }}

      - name: Otherwise
        uses: ./.github/actions/otherwise/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && !contains('><+-.,[]', steps.values.outputs.CURRENT_CHARACTER) }}

      - name: Basis
        id: basis
        uses: ./.github/actions/basis/
        if: ${{ !(fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH)) }}

      #==============================================================================
      - uses: actions/cache/save@v4
        with:
          path: |
            context.json
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

      - run: sleep 5
      - name: Fire this workfllow recursively if not finished
        uses: ./.github/actions/empty-commit-to-branch/
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch-name: dummy-main
        if: ${{ steps.basis.outputs.is-finished != 'true' }}
