name: "Main: Brainfuck interpreter by GitHub Actions"

on:
  push:
    branches:
      - dummy

jobs:
  entrypoint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Restore context
        uses: actions/cache/restore@v4
        with:
          path: |
            phase
            preprocessing-state
            program-state
            character-to-number
            number-to-character
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-

      - id: phase
        run: cat <<<"VALUE=$( cat phase )" >> $GITHUB_OUTPUT
      - name: Stop this job if current phase is not `main`
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.phase.outputs.VALUE != 'main' }}

      #==============================================================================
      # Main
      - name: Evaluates values to be used later
        id: values
        working-directory: program-state
        run: |
          cat <<< "CURRENT_PROGRAM_POSITION=$(cat current-program-position)" >> $GITHUB_OUTPUT
          cat <<< "PROGRAM_LENGTH=$(( $(cat program | wc -c) - 1 ))" >> $GITHUB_OUTPUT # -1 for the newline character
          PROGRAM="$(cat program)"
          cat <<< "CURRENT_CHARACTER=${PROGRAM:$(cat current-program-position):1}" >> $GITHUB_OUTPUT

      - name: ">"
        uses: ./.github/actions/brainfuck-main/>/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '>' }}

      - name: "<"
        uses: ./.github/actions/brainfuck-main/</
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '<' }}

      - name: "+"
        uses: ./.github/actions/brainfuck-main/+/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '+' }}

      - name: "-"
        uses: ./.github/actions/brainfuck-main/-/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '-' }}

      - name: "."
        uses: ./.github/actions/brainfuck-main/_./
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '.' }}

      - name: ","
        uses: ./.github/actions/brainfuck-main/,/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == ',' }}

      - name: "["
        uses: ./.github/actions/brainfuck-main/[/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == '[' }}

      - name: "]"
        uses: ./.github/actions/brainfuck-main/]/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && steps.values.outputs.CURRENT_CHARACTER == ']' }}

      - name: Otherwise
        uses: ./.github/actions/brainfuck-main/otherwise/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) && !contains('><+-.,[]', steps.values.outputs.CURRENT_CHARACTER) }}

      - name: Basis
        id: basis
        uses: ./.github/actions/brainfuck-main/basis/
        if: ${{ !(fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH)) }}

      #==============================================================================
      - uses: actions/cache/save@v4
        with:
          path: |
            phase
            preprocessing-state
            program-state
            character-to-number
            number-to-character
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

      - run: sleep 5
      - name: Fire this workfllow recursively if not finished
        uses: ./.github/actions/empty-commit-to-branch/
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch-name: dummy
        if: ${{ steps.basis.outputs.is-finished != 'true' }}
