name: "Preprocessing: Brainfuck interpreter by GitHub Actions"

on:
  push:
    branches:
      - dummy

jobs:
  entrypoint:
    runs-on: ubuntu-22.04

    permissions:
      actions: "write"

    steps:
      - uses: actions/checkout@v4
      - name: Restore stack
        uses: actions/cache/restore@v4
        with:
          path: |
            phase
            preprocessing-state
            program-state
            character-to-number
            number-to-character
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-

      - id: phase
        run: cat <<<"VALUE=$( cat phase )" >> $GITHUB_OUTPUT
      - name: Stop this job if current phase is not `preprocessing`
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.phase.outputs.VALUE != 'preprocessing' }}

      #==============================================================================
      # Main
      - name: Debug print
        working-directory: preprocessing-state
        run: |
          cat stack
          cat <<<'' # break line
          cat current-program-position

      - name: Evaluates values to be used later
        id: values
        working-directory: preprocessing-state
        run: |
          cat <<<"PROGRAM=$(cat program)" >> $GITHUB_OUTPUT
          cat <<<"CURRENT_PROGRAM_POSITION=$(cat current-program-position)" >> $GITHUB_OUTPUT
          cat <<<"PROGRAM_LENGTH='$(cat program | wc -c)'" >> $GITHUB_OUTPUT
          cat <<<"STDIN='$(cat stdin)'" >> $GITHUB_OUTPUT

      - name: Create transition function
        uses: ./.github/actions/brainfuck-preprocessing/create-transition-function/
        if: ${{ fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH) }}

      - name: Crash if the program scanning is completed and there are any values left on the stack
        id: stack-length
        working-directory: preprocessing-state
        run: |
          cat <<<"VALUE='$(cat stack | wc -c)'" >> $GITHUB_OUTPUT
      - run: |
          cat stack
          exit 1
        if: ${{ !(fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH)) && fromJson(steps.stack-length.outputs.VALUE) > 0 }}

      - name: Create program state if the program scanning is completed
        uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
        if: ${{ !(fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH)) }}

      #==============================================================================
      - name: Switch the phase if finished
        run: cat <<<'main' >phase
        if: ${{ !(fromJson(steps.values.outputs.CURRENT_PROGRAM_POSITION) < fromJson(steps.values.outputs.PROGRAM_LENGTH)) }}

      - uses: actions/cache/save@v4
        with:
          path: |
            phase
            preprocessing-state
            program-state
            character-to-number
            number-to-character
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

      - run: sleep 5

      - name: Fire next workfllow
        uses: ./.github/actions/empty-commit-to-branch/
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch-name: dummy
