name: Test each branch of this brainfuck implementation

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  gt: # >
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '>>' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/>/
      - uses: ./.github/actions/brainfuck-main/>/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "2"
          test "$(cat current-memory-position)" = "2"

  lt: # <
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '<<' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/</
      - uses: ./.github/actions/brainfuck-main/</

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "2"
          test "$(cat current-memory-position)" = "-2"

  plus: # +
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '++' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/+/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "2"
          test "$(cat memory_0)" = "2"

  minus: # -
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '--' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/-/
      - uses: ./.github/actions/brainfuck-main/-/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "2"
          test "$(cat memory_0)" = "-2"

  dot: # .
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '..' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      - run: cd program-state && echo '65' >memory_0
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/_./
      - uses: ./.github/actions/brainfuck-main/_./

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "2"
          test "$(cat stdout)" = "AA"

  comma: # ,
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo ',>,' > program
          echo 'AB' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/,/
      - uses: ./.github/actions/brainfuck-main/>/
      - uses: ./.github/actions/brainfuck-main/,/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "3"
          test "$(cat memory_0)" = "65"
          test "$(cat memory_1)" = "66"

  left-parenthesis1: # [
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '[xxx]' > program
          echo '4' > transition-function_0
          echo '0' > transition-function_4
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/[/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "5"

  left-parenthesis2: # [
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '[xxx]' > program
          echo '4' > transition-function_0
          echo '0' > transition-function_4
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      - run: cd program-state && echo '1' > memory_0 # The value to be written can be any non-zero number.
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/[/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "1"

  right-parenthesis1: # ]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '[xxx]' > program
          echo '4' > transition-function_0
          echo '0' > transition-function_4
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      - run: |
          cd program-state
          echo '4' > current-program-position # `]` position
          echo '1' > memory_0 # The value to be written can be any non-zero number.
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/]/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "1"

  right-parenthesis2: # ]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '[xxx]' > program
          echo '4' > transition-function_0
          echo '0' > transition-function_4
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      - run: |
          cd program-state && echo '4' > current-program-position # `]` position
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/]/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "5"

  otherwise: # Otherwise
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo 'x' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/otherwise/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat current-program-position)" = "1"

  basis: # Basis
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '' > program
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        id: basis
        uses: ./.github/actions/brainfuck-main/basis/

      - name: Verify
        working-directory: program-state
        run: |
          test "${{ steps.basis.outputs.is-finished }}" = "true"

  two-plus-five:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir program-state preprocessing-state character-to-number number-to-character
          cd preprocessing-state
          echo '++>+++++<[->+<]' > program
          echo 14 > transition-function_9
          echo 9 > transition-function_14
          echo '' > stdin
      - uses: ./.github/actions/brainfuck-preprocessing/create-program-state/
      #
      - name: Exercise
        uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/>/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/</
      #
      - uses: ./.github/actions/brainfuck-main/[/
      - uses: ./.github/actions/brainfuck-main/-/
      - uses: ./.github/actions/brainfuck-main/>/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/</
      - uses: ./.github/actions/brainfuck-main/]/
      #
      - uses: ./.github/actions/brainfuck-main/[/
      - uses: ./.github/actions/brainfuck-main/-/
      - uses: ./.github/actions/brainfuck-main/>/
      - uses: ./.github/actions/brainfuck-main/+/
      - uses: ./.github/actions/brainfuck-main/</
      - uses: ./.github/actions/brainfuck-main/]/
      #
      - uses: ./.github/actions/brainfuck-main/[/
      - uses: ./.github/actions/brainfuck-main/basis/

      - name: Verify
        working-directory: program-state
        run: |
          test "$(cat memory_1)" = "7"
