name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: denoland/setup-deno@v1
      - uses: actions/checkout@v4
      - name: Test
        run: deno test
