name: Entry point for Brainfuck interpreter by GitHub Actions

on:
  workflow_dispatch:
    inputs:
      program:
        description: Brainfuck program
        required: true
        type: string
      stdin:
        description: String to be input in the standard input
        required: false
        type: string
        default: ""

jobs:
  entrypoint:
    runs-on: ubuntu-22.04

    steps:
      - uses: denoland/setup-deno@v1
      - uses: actions/checkout@v4

      - name: Create context
        run: deno run --allow-read createContext.ts "${{ inputs.program }}" "${{ inputs.stdin }}" > context.json

      - name: Save context.json
        uses: actions/cache/save@v4
        with:
          path: |
            context.json
          key: ${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}

      - uses: ./.github/actions/empty-commit-to-dummy-branch/
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
