name: Initialize brainfuck

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Remove all caches
        run: gh cache list --json id --jq 'map(.id)[]' | xargs -I{} -P0 gh cache delete {}

      - name: Remove dummy branch
        run: |
          git push origin -d dummy-main || true
          git push origin -d dummy-preprocessing || true
      - name: Create dummy branch
        run: |
          branch_name=$( echo ${"$( git branch -q --contains "$( git log --all --format='%H' -1 )" )":2} )
          git checkout "$branch_name"
          git checkout -b dummy-main
          git push origin dummy-main

          git checkout "$branch_name"
          git checkout -b dummy-preprocessing
          git push origin dummy-preprocessing
